name:                wkt-types
version:             0.1.0.0
github:              "gtollini/wkt-types"
license:             BSD-3-Clause
author:              "Gabriel Tollini"
maintainer:          "gabrieltollini@hotmail.com"
copyright:           "2024 Gabriel Tollini"

extra-doc-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
synopsis:            A library for working with .wkt files.
category:            Geometry, GIS, Parser, WKT, OGC, Well-Known-Text

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/gtollini/wkt-types#readme>

dependencies:
- base >= 4.7 && < 5
- attoparsec >= 0.14.4 && < 0.15
- bytestring >= 0.12.1 && < 0.13
- text >= 2.1.1 && < 2.2
- hspec >= 2.11.9 && < 2.12

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

tests:
  wkt-types-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - wkt-types
